function [time, dose_rate] = import_drug_data(filename, dataLines)
    % IMPORT_DRUG_DATA Import data from a text file
    %  [TIME, DOSE_RATE] =
    %  IMPORT_DRUG_DATA(FILENAME) reads data from text file FILENAME for the
    %  default selection.  Returns the data as column vectors.
    %
    %  [TIME, DOSE_RATE] =
    %  IMPORT_DRUG_DATA(FILE, DATALINES) reads data for the specified row
    %  interval(s) of text file FILENAME. Specify DATALINES as a positive
    %  scalar integer or a N-by-2 array of positive scalar integers for
    %  dis-contiguous row intervals.
    %
    %  Example:
    %  [time, dose_rate] = import_drug_data("/path/to/17-Nov-2023 Infusion.txt", [2, Inf]);
    %
    %  See also READTABLE.
    %
    % Auto-generated by MATLAB on 28-Nov-2023 15:50:25
    
    % Input handling
    
    % If dataLines is not specified, define defaults
    if nargin < 2
        dataLines = [2, Inf];
    end
    
    % Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 6);
    
    % Specify range and delimiter
    opts.DataLines = dataLines;
    opts.Delimiter = ",";
    
    % Specify column names and types
    opts.VariableNames = ["time", "drug_conc", "total_dose", "rat_weight", "dose_vol", "rate"];
    opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double"];
    
    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    
    % Specify variable properties
    opts = setvaropts(opts, "time", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");
    
    % Import the data
    tbl = readtable(filename, opts);

    % find correct restart time of basal rate
    calc_time_inds = find(isnat(tbl.time));
    tbl.time(calc_time_inds) = tbl.time(calc_time_inds-1) + minutes(tbl.dose_vol(calc_time_inds-1)./tbl.rate(calc_time_inds-1));
    
    % Convert to output type
    time_on = tbl.time;
    total_dose = tbl.total_dose;
    time_given = tbl.dose_vol./tbl.rate;
    
    % Calculation to determine end time of specific type of input
    time_off = time_on+minutes(time_given);
%     delete_off = find([time_off(1:end-1)>time_on(2:end)]);
    insert_off = find([time_off(1:end-1)<time_on(2:end);true]);
    time_off = time_off(insert_off);

    time = sort([time_on; time_off]);

    % calculate dose rate
    dose_rate = total_dose./time_given/60*1000; % ug/kg/s

    
    for ind = flipud(insert_off)'
        dose_rate = [dose_rate(1:ind); 0; dose_rate(1+ind:end)];
    end
    
    % old code for when pump always went to 0 after dose
%     dose_rate = reshape([dose_rate zeros(size(dose_rate))]', [], 1);   
%     dose_rate(2*delete_off) = [];

end