function [tCO2,Temp,CO2, start_time] = import_time_temp_CO2(filename,startstring)
%IMPORT_TIME_TEMP_CO2 Import numeric data from a text file as column vectors.
%   [TCO2,TEMP,CO2] = IMPORT_TIME_TEMP_CO2(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   [TCO2,TEMP,CO2] = IMPORT_TIME_TEMP_CO2(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [tCO2,Temp,CO2] = import_time_temp_CO2('230106 Rat SCAR.txt',1, 149777);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2023/01/09 14:02:43

% Initialize variables.
if nargin<=2
    startRow = 1;
    endRow = inf;
end

% Format for each line of text:
%   column4: double (%f)
%	column5: double (%f)
%   column6: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%11f%8f%s%[^\n\r]';

% Open the text file.
fileID = fopen(filename,'r');

% scan for start
keepgoing = ~isempty(startstring);
start_time = [];

while keepgoing
    % Read the next line.
	textLine = fgetl(fileID);
	
    if contains(textLine,startstring)
        start_time = textLine;
		keepgoing = false;
    end	
end

% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', ["\t","\t<CL>"], 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'TreatAsEmpty', '*', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', ["\t","\t<CL>"], 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'TreatAsEmpty', '*', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

% Close the text file.
fclose(fileID);

% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.

% Allocate imported array to column variable names
actual_seconds = dataArray{:, 2};
[actual_seconds, I] = sort(actual_seconds);
tCO2 = dataArray{:, 1};
tCO2 = datetime(tCO2(1),'InputFormat', 'M/d/yyyy h:mm:ss a,S')+seconds(actual_seconds)-seconds(actual_seconds(1));
Temp = dataArray{:, 3};
CO2 = dataArray{:, 4};

CO2 = dataArray{:, 4};
errors = find(contains(CO2, "<CL>"));

fixes = char(CO2(errors));
if ~isempty(fixes)
    fixes = string(fixes(:, end-5:end));
end

CO2(errors) = fixes;
CO2 = double(CO2);

Temp = Temp(I);
CO2 = CO2(I);


