function [time, vac_setting] = import_ratcuum(filename, dataLines)
    % IMPORT_RATCUUM Import data from a text file
    %  [TIME, VAC_SETTING] =
    %  IMPORT_RATCUUM(FILENAME) reads data from text file FILENAME for the
    %  default selection.  Returns the data as column vectors.
    %
    %  [TIME, VAC_SETTING] =
    %  IMPORT_RATCUUM(FILE, DATALINES) reads data for the specified row
    %  interval(s) of text file FILENAME. Specify DATALINES as a positive
    %  scalar integer or a N-by-2 array of positive scalar integers for
    %  dis-contiguous row intervals.
    %
    %  Example:
    %  [time, vac_setting] = import_ratcuum("/path/to/17-Nov-2023 Ratcuum.txt", [2, Inf]);
    %
    %  See also READTABLE.
    %
    % Auto-generated by MATLAB on 28-Nov-2023 15:50:25
    
    % Input handling
    
    % If dataLines is not specified, define defaults
    if nargin < 2
        dataLines = [2, Inf];
    end
    
    % Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 3);
    
    % Specify range and delimiter
    opts.DataLines = dataLines;
    opts.Delimiter = ";";
    
    % Specify column names and types
    opts.VariableNames = ["Time", "BP_drop", "cal_coef"];
    opts.VariableTypes = ["datetime", "double", "double"];
    
    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    
    % Specify variable properties
    opts = setvaropts(opts, "Time", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");
    
    % Import the data
    tbl = readtable(filename, opts);
    
    % Convert to output type
    time = tbl.Time;
    vac_setting = round(tbl.BP_drop .* tbl.cal_coef/10);
    

end