function [StartTime, EndTime] = import_times(filename, dataLines)
%IMPORT_TIMES Import data from a text file
%  [STARTTIME, ENDTIME] = IMPORT_TIMES(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [STARTTIME, ENDTIME] = IMPORT_TIMES(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [StartTime, EndTime] = import_times("/path/to/Challenge Trials/LBNP Closed Loop/Trace Timings.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Sep-2024 13:36:17

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["StartTime", "EndTime"];
opts.VariableTypes = ["datetime", "datetime"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, "StartTime", "InputFormat", "yyyyMMdd HHmmss", "DatetimeFormat", "preserveinput");
opts = setvaropts(opts, "EndTime", "InputFormat", "yyyyMMdd HHmmss", "DatetimeFormat", "preserveinput");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
StartTime = tbl.StartTime;
EndTime = tbl.EndTime;
end